[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
onchain = "6h1imPy2SzZNBUa535uy2hcCWj2WFYbeMw5Qgnurtbom"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
